### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by Zachillesaa** [Shiaoming/Python-VO#1]
Thank you for your good work. I encountered this problem when used
$ python main.py

Traceback (most recent call last):
  File "main.py", line 124, in <module>
    run(args)
  File "main.py", line 110, in run
    cv2.imwrite("results/" + fname + '_new.png', img2)
UnboundLocalError: local variable 'img2' referenced before assignment

then,I put cv2.imwrite() into for()
it works ,but the four methods all just load the model,like this 
INFO:root:{'descriptor_dim': 256, 'weights': 'outdoor', 'keypoint_encoder': [32, 64, 128, 256], 'GNN_layers': ['self', 'cross', 'self', 'cross', 'self', 'cross', 'self', 'cross', 'self', 'cross', 'self', 'cross', 'self', 'cross', 'self', 'cross', 'self', 'cross'], 'sinkhorn_iterations': 100, 'match_threshold': 0.2, 'cuda': 1, 'type': 'SuperGlue'}
INFO:root:creating SuperGlue matcher...
Loaded SuperGlue model ("outdoor" weights)

Thank you.

**Comment by Shiaoming** [comment]
This happens when there is no image for the data loader to enumerate, so the for-loop (line: 94~108) is skipped.

Please check your dataset configures and dataset directories.

**Comment by Zachillesaa** [comment]
I add a '/' ,it works.
Thanks for your help.
