### ISSUE TITLE
how to visualize Superpoint+FLANN Matches?

### ISSUE THREAD

**Issue by lisaring** [Shiaoming/Python-VO#7]
![image](https://user-images.githubusercontent.com/15711091/103845035-2f329680-50d6-11eb-9434-ab3fbe4e8555.png)
how to get this visualization in the code? Thank you.

**Comment by Shiaoming** [comment]
check this function: 
https://github.com/Shiaoming/Python-VO/blob/c03e88fed01985a008eca14c8b49f8644fbf6d74/utils/tools.py#L38-L91

**Comment by lisaring** [comment]
> check this function:
> https://github.com/Shiaoming/Python-VO/blob/c03e88fed01985a008eca14c8b49f8644fbf6d74/utils/tools.py#L38-L91

**Comment by lisaring** [comment]
> check this function:
> https://github.com/Shiaoming/Python-VO/blob/c03e88fed01985a008eca14c8b49f8644fbf6d74/utils/tools.py#L38-L91

Thank you.
